# -*- coding: utf-8 -*-
"""Week11HackOweek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcFtz4-wpyneGujRAICVkd57gau2Uh0v
"""

# 1. Install necessary libraries
!pip install flask-bcrypt PyJWT flask-cors

import jwt
import datetime
from flask import Flask, request, jsonify
from flask_bcrypt import Bcrypt
from flask_cors import CORS

app = Flask(__name__)
CORS(app)
bcrypt = Bcrypt(app)

# SECRET_KEY for JWT - Keep this very secure in production!
app.config['SECRET_KEY'] = 'your_super_secret_hack_o_week_key'

# Simple in-memory "Database"
users_db = {}

# --- API ROUTES ---

@app.route('/register', methods=['POST'])
def register():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')

    if email in users_db:
        return jsonify({"message": "User already exists"}), 400

    # Encrypt password (requirement: store encrypted user profiles)
    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
    users_db[email] = {
        "password": hashed_password,
        "name": data.get('name', 'User')
    }

    return jsonify({"message": "User registered successfully!"}), 201

@app.route('/login', methods=['POST'])
def login():
    data = request.get_json()
    email = data.get('email')
    password = data.get('password')

    user = users_db.get(email)

    # Check password and generate JWT
    if user and bcrypt.check_password_hash(user['password'], password):
        token = jwt.encode({
            'user': email,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=30)
        }, app.config['SECRET_KEY'], algorithm="HS256")

        return jsonify({"token": token, "message": "Login Successful!"})

    return jsonify({"message": "Invalid Credentials"}), 401

# --- SIMULATION SECTION ---
# Since we can't easily run a persistent server in a single cell,
# let's simulate the API calls to show it works.

print("--- TESTING PROJECT 11 LOGIC ---")

# Simulate Registration
test_user = {"email": "student@college.edu", "password": "securePassword123", "name": "HackoWeek User"}
hashed = bcrypt.generate_password_hash(test_user['password']).decode('utf-8')
users_db[test_user['email']] = {"password": hashed, "name": test_user['name']}
print(f"1. User Registered: {test_user['email']}")

# Simulate Login & JWT Generation
if bcrypt.check_password_hash(users_db[test_user['email']]['password'], "securePassword123"):
    token = jwt.encode({
        'user': test_user['email'],
        'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=30)
    }, app.config['SECRET_KEY'], algorithm="HS256")
    print(f"2. Login Successful! JWT Generated: \n{token}")

# Simulate Token Verification
decoded = jwt.decode(token, app.config['SECRET_KEY'], algorithms=["HS256"])
print(f"\n3. Token Verified for User: {decoded['user']}")

# 1. Install required security libraries
!pip install flask-bcrypt PyJWT

import jwt
import datetime
from flask_bcrypt import Bcrypt
from IPython.display import HTML, display

# Initialize security tools
bcrypt = Bcrypt()
SECRET_KEY = "campus_secure_key_2026"
users_db = {} # Simple in-memory storage for the hackathon

def register_user(name, email, password):
    # Requirement: Store encrypted user profiles
    hashed_pw = bcrypt.generate_password_hash(password).decode('utf-8')
    users_db[email] = {"name": name, "password": hashed_pw}

    # Requirement: Generate JWT upon registration/login
    token = jwt.encode({
        'user': email,
        'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=1)
    }, SECRET_KEY, algorithm="HS256")

    return token

# --- RENDER FRONTEND UI ---
html_code = """
<div style="font-family: Arial; border: 1px solid #ccc; padding: 20px; border-radius: 10px; width: 300px; background: #f9f9f9;">
    <h3>User Registration Portal</h3>
    <input type="text" id="name" placeholder="Full Name" style="width: 100%; margin-bottom: 10px;"><br>
    <input type="email" id="email" placeholder="Email" style="width: 100%; margin-bottom: 10px;"><br>
    <input type="password" id="password" placeholder="Password" style="width: 100%; margin-bottom: 10px;"><br>
    <button onclick="submitData()" style="width: 100%; background: #28a745; color: white; padding: 10px; border: none; cursor: pointer;">Register & Generate JWT</button>
    <div id="output" style="margin-top: 15px; font-size: 12px; word-wrap: break-word; color: #333;"></div>
</div>

<script>
async function submitData() {
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const pass = document.getElementById('password').value;
    const output = document.getElementById('output');

    if(!name || !email || !pass) {
        output.innerHTML = "<b style='color:red;'>Please fill all fields!</b>";
        return;
    }

    // This simulates calling the Python backend in Colab
    google.colab.kernel.invokeFunction('notebook.register', [name, email, pass], {});
}
</script>
"""

display(HTML(html_code))

# --- BACKEND CONNECTOR ---
import google.colab.output

def notebook_register(name, email, password):
    token = register_user(name, email, password)
    print(f"\n[BACKEND] Registration Success for: {name}")
    print(f"[BACKEND] Profile Encrypted with Bcrypt")
    print(f"[BACKEND] JWT TOKEN GENERATED:\n{token}")

    # Show success message in UI
    with google.colab.output.redirect_to_element('#output'):
        display(HTML(f"<b style='color:green;'>Success!</b><br><b>JWT:</b> <span style='font-family:monospace;'>{token[:40]}...</span>"))

google.colab.output.register_callback('notebook.register', notebook_register)

