# -*- coding: utf-8 -*-
"""Week12HackOweek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sup8Y79khjqXDkI6kor86DdJ-DH62JQK
"""

# 1. Install required libraries
!pip install flask-socketio cryptography flask-cors

import json
import base64
from flask import Flask
from flask_socketio import SocketIO, emit
from cryptography.fernet import Fernet
from IPython.display import HTML, display

# --- ENCRYPTION SETUP ---
# Generate a key for the Fernet symmetric encryption
key = Fernet.generate_key()
cipher_suite = Fernet(key)

app = Flask(__name__)
socketio = SocketIO(app, cors_allowed_origins="*")

# --- BACKEND LOGIC ---
def encrypt_and_store(data):
    # Convert dictionary to JSON string then to bytes
    json_payload = json.dumps(data).encode()

    # REQUIREMENT: Encrypt payloads before database insert
    encrypted_token = cipher_suite.encrypt(json_payload)

    # Simulation: Printing the encrypted 'blob' that would go to your DB
    return encrypted_token

# --- RENDER FRONTEND SIMULATOR ---
# This simulates a wearable device sending heart rate and steps
html_ui = """
<div style="font-family: Arial; border: 1px solid #333; padding: 20px; border-radius: 10px; width: 350px; background: #222; color: #0f0;">
    <h3 style="color: white;">Wearable Device Simulator</h3>
    <p>Heart Rate: <span id="hr_val">72</span> BPM</p>
    <p>Steps: <span id="step_val">1200</span></p>
    <button onclick="sendData()" style="width: 100%; background: #007bff; color: white; padding: 10px; border: none; cursor: pointer; border-radius: 5px;">
        Send via WebSocket (Encrypted)
    </button>
    <div id="log" style="margin-top: 15px; font-size: 11px; color: #aaa; background: #000; padding: 5px; height: 80px; overflow-y: auto;"></div>
</div>

<script>
function sendData() {
    // Generate random wearable data
    const hr = Math.floor(Math.random() * (100 - 60 + 1)) + 60;
    const steps = Math.floor(Math.random() * 10000);

    document.getElementById('hr_val').innerText = hr;
    document.getElementById('step_val').innerText = steps;

    // Call the Python backend logic
    google.colab.kernel.invokeFunction('notebook.ingest', [hr, steps], {});
}
</script>
"""

display(HTML(html_ui))

# --- COLAB BACKEND CONNECTOR ---
import google.colab.output

def notebook_ingest(hr, steps):
    wearable_data = {"heart_rate": hr, "steps": steps}

    # Process the data
    encrypted_blob = encrypt_and_store(wearable_data)

    print(f"\n[WEBSOCKET] Received Data: HR={hr}, Steps={steps}")
    print(f"[SECURITY] Payload Encrypted successfully.")
    print(f"[STORAGE] Saving to DB: {encrypted_blob[:50].decode()}...")

google.colab.output.register_callback('notebook.ingest', notebook_ingest)

